Update 27322_test.yml

diff --git a/.github/workflows/27322_test.yml b/.github/workflows/27322_test.yml
--- a/.github/workflows/27322_test.yml
+++ b/.github/workflows/27322_test.yml
@@ -1,1 +1,47 @@
+name: CI
 
+on: [push]
+
+jobs:
+  posel_1:
+    name: Check if test_main.cpp exists
+    runs-on: self-hosted
+    steps:
+      - name: Check if test_main.cpp exists
+        run: |
+          if [ ! -f test_main.cpp ]; then
+            echo "test_main.cpp not found, exiting workflow" > napaka.txt
+            exit 1
+          fi
+          echo "Obstaja" > napaka.txt
+
+      - name: Upload napaka.txt as an artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: naloga_pred
+          path: napaka.txt
+
+  posel_2:
+    name: Test
+    runs-on: self-hosted
+    needs: posel_1
+    steps:
+      - name: Download napaka.txt artifact from posel_1
+        uses: actions/download-artifact@v4
+        with:
+          name: naloga_pred
+
+      - name: Check if napaka.txt has content "Obstaja"
+        run: |
+          if ! grep -q "Obstaja" napaka.txt; then
+            echo "Error: napaka.txt does not contain 'Obstaja', exiting workflow"
+            exit 1
+          fi
+      - name: Compile C++ code
+        run: |
+          g++ -c main.cpp -o main.o
+          g++ -c test_main.cpp -o test_main.o
+          g++ main.o test_main.o -o test_executable
+
+      - name: Run tests
+        run: ./test_executable
