Update simple.yaml

diff --git a/.github/workflows/simple.yaml b/.github/workflows/simple.yaml
--- a/.github/workflows/simple.yaml
+++ b/.github/workflows/simple.yaml
@@ -1,32 +1,44 @@
-
 name: CI
 
-# Controls when the action will run. Triggers the workflow on push or pull request
-# events but only for the main branch
 on: [push]
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-
-# This workflow contains a single job called "build"
 jobs:
-  # The build job runs on an ubuntu-latest machine
   posel_1:
     name: Check if test_main.cpp exists
     runs-on: self-hosted
     steps:
-      - uses: actions/upload-artifact@v4
-
       - name: Check if test_main.cpp exists
         run: |
-          if [ ! -f test_mainn.cpp ]; then
+          if [ ! -f test_main.cpp ]; then
             echo "test_main.cpp not found, exiting workflow"
             exit 1
           fi
-          
-          with:
+
+      - name: Upload napaka.txt as an artifact
+        uses: actions/upload-artifact@v4
+        with:
           name: naloga_pred
           path: napaka.txt
+
   posel_2:
-    name: test
+    name: Test
     runs-on: self-hosted
     needs: posel_1
+    steps:
+      - name: Download napaka.txt artifact from posel_1
+        uses: actions/download-artifact@v4
+        with:
+          name: naloga_pred
+          path: .
+
+      - name: Check if napaka.txt exists
+        run: |
+          if [ -f napaka.txt ]; then
+            echo "Error: napaka.txt found, exiting workflow"
+            exit 1
+          fi
+
+      - name: Run tests
+        run: |
+          # Command to compile and run tests goes here
+          echo "Running tests..."
