Update simple.yaml

diff --git a/.github/workflows/simple.yaml b/.github/workflows/simple.yaml
--- a/.github/workflows/simple.yaml
+++ b/.github/workflows/simple.yaml
@@ -22,6 +22,13 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
+      - name: Check if test_main.cpp exists
+        run: |
+          if [ ! -f test_main.cpp ]; then
+            echo "test_main.cpp not found, exiting workflow"
+            exit 1
+          fi
+
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world! > log.txt
